version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mypassport-db
    restart: always
    environment:
      MYSQL_DATABASE: mypassport
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3308:3308"
    volumes:
      - db_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  db_data:
