spring:
  application:
    name: MyPassport
  profiles:
    active: dev
  
  # Shared Configuration
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  
  flyway:
    enabled: true
    baseline-on-migrate: true

# Common Server Config (can be overridden in profiles)
server:
  port: 8089