spring:
  application:
    name: MyPassport
  datasource:
    # H2 Database (Default)
    # url: jdbc:h2:mem:testdb
    # driver-class-name: org.h2.Driver
    # username: sa
    # password:

    # MySQL Database (Docker)
    url: jdbc:mysql://localhost:3308/mypassport?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

server:
  port: 8089